"""Initial revision

Revision ID: 5bb298725f09
Revises: 
Create Date: 2025-03-31 20:36:39.561807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb298725f09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ручное преобразование VARCHAR → DATE
    op.execute("""
        ALTER TABLE birthdays
        ALTER COLUMN birth_date TYPE DATE
        USING birth_date::date
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('birthdays', 'birth_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
